name: bdh
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  provider:
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  shared_preferences: ^2.2.2

  flutter_barcode_scanner: ^2.0.0
  dio: ^5.3.3
  awesome_snackbar_content: ^0.1.3
  url_launcher: ^6.2.2
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  quickalert: ^1.0.2
  flutter_slidable: ^3.0.1
  flutter_animate: ^4.3.0
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  flutter_windowmanager: ^0.2.0
  awesome_dialog: ^3.2.0
  popover: ^0.2.8+2
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/auth.jpg
    - assets/images/roadImage.png
    - assets/images/readImage1.png
    - assets/images/readImage2.png
    - assets/images/background.png
    - assets/images/golden.png
    - assets/images/bronze.png
    - assets/images/circle.png
    - assets/images/openbook.png
    - assets/images/circleBackground.png
    - assets/images/backRoad.png
    - assets/images/road.png
    - assets/images/bookCover.jpg
    - assets/images/silver.png
    - assets/lotties/scroll.json
    - assets/lotties/read.json
    - assets/lotties/read2.json
    - assets/lotties/catReading.json
    - assets/lotties/catReading2.json
    - assets/lotties/roadCick.json
    - assets/lotties/roadCick2.json
    - assets/lotties/empty.json
    - assets/lotties/step.json
    - assets/images/auth1.jpg
    - assets/images/auth2.jpg
    - assets/images/englishClubText.png
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_ff/AvenirLTStd-Book.otf
    - family: Messiri
      fonts:
        - asset: assets/fonts/Messiri/ElMessiri-Regular.ttf
