name: bdh
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  provider: ^6.1.2
  google_nav_bar: ^5.0.6
  image_picker: ^1.1.1
  shared_preferences: ^2.2.3
  # flutter_barcode_scanner: ^2.0.0
  dio: ^5.4.3+1
  awesome_snackbar_content: ^0.1.3
  url_launcher: ^6.2.6
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  quickalert: ^1.1.0
  flutter_slidable: ^3.1.0
  flutter_animate: ^4.5.0
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  flutter_windowmanager: ^0.2.0
  awesome_dialog: ^3.2.1
  popover: ^0.3.0+1
  percent_indicator: ^4.2.3
  pretty_qr_code: ^3.3.0
  qr_flutter: ^4.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_speed_dial: ^7.0.0
  screenshot: ^3.0.0
  esys_flutter_share_plus: ^2.2.0
  transparent_image: ^2.0.1
  flutter_phoenix: ^1.1.1
  firebase_messaging: ^14.9.3
  firebase_core: ^2.31.1
  flutter_local_notifications: ^17.1.2
  awesome_notifications: ^0.9.3+1
  device_info_plus: ^10.1.0
  barcode_scan2: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/auth.jpg
    - assets/images/roadImage.png
    - assets/images/test.png
    - assets/images/readImage1.png
    - assets/images/openBookTitle.png
    - assets/images/readImage2.png
    - assets/images/borrowBook.png
    - assets/images/background.png
    - assets/images/studentScore.png
    - assets/images/homeBack.png
    - assets/images/studentLevel.png
    - assets/images/finishedStudentStories.png
    - assets/images/golden.png
    - assets/images/bronze.png
    - assets/images/circle.png
    - assets/images/openbook.png
    - assets/images/circleBackground.png
    - assets/images/backRoad.png
    - assets/images/road.png
    - assets/images/bookCover.jpg
    - assets/images/silver.png
    - assets/lotties/scroll.json
    - assets/lotties/read.json
    - assets/lotties/read2.json
    - assets/lotties/catReading.json
    - assets/lotties/noData.json
    - assets/lotties/catReading2.json
    - assets/lotties/roadCick.json
    - assets/lotties/roadCick2.json
    - assets/lotties/empty.json
    - assets/lotties/step.json
    - assets/images/auth1.jpg
    - assets/lotties/celebrate.json
    - assets/images/auth2.jpg
    - assets/images/englishClubText.png
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_ff/AvenirLTStd-Book.otf
    - family: Messiri
      fonts:
        - asset: assets/fonts/Messiri/ElMessiri-Regular.ttf
